### ISSUE TITLE
Refactor gulpfile into single build file using npm_lifecycle

### ISSUE THREAD

**Issue by adam-cyclones** [rockcarver/frodo-lib#227]
## Description:
The current build process relies on Gulp and has several tasks defined in the gulpfile. We want to refactor this to use a single script instead of Gulp, which will simplify the build process and reduce the number of dependencies.

The new script should detect the npm lifecycle events and run the appropriate tasks. For example, if the user runs npm run clean-esm, it should call rmRF('esm'). If the user runs npm run transpile-esm, it should call babel('src', { outDir: 'build', sourceMaps: true }). Similarly, it should call the appropriate functions for other tasks like create-mjs-esm, resources-esm, transpile-cjs, resources-cjs, generate-types, and build.

The script should prefer to use the Node.js API functions like rmRF(), mkdir(), copyFile(), readdir(), etc. over the exec() or spawn() functions whenever possible. If it's not possible to use the Node.js API functions, it can fall back to exec() or spawn().

We should also add comments to the script explaining what each task does and how it works. This will make it easier for developers to understand and modify the build process in the future.

Once the script is ready, we should update the scripts section of package.json to use the new script instead of Gulp.

It would also be ideal of this build script ran using ts-node so we don't have to build it and can keep the typescript even in the build process.

### Proposed scripts to re-create
Aprox generated by ChatGPT

- clean-esm: Removes the esm directory.
- clean-build: Removes the build directory.
- clean-cjs: Removes the cjs directory.
- clean-types: Removes the types directory.
- transpile-esm: Transpiles the TypeScript code in the src directory using Babel, and outputs the transpiled code to the build  directory with source maps.
- create-mjs-esm: Renames all JavaScript files in the build directory to have a .mjs extension.
- resources-esm: Copies all JSON, TXT, and XML files from the src directory to the esm directory.
- transpile-cjs: Transpiles the TypeScript code in the src directory using Babel, and outputs the transpiled code to the cjs directory with source maps, using a different Babel config file than transpile-esm.
- resources-cjs: Copies all JSON, TXT, and XML files from the src directory to the cjs directory.
- generate-types: Generates TypeScript declaration files from the code in the src directory, and outputs them to the types directory with source maps.
- build: Runs all of the above build commands in sequence.
- watch: Starts a watch task that runs the build command whenever any file in the src directory or its subdirectories changes.

**Comment by adam-cyclones** [comment]
Still in progress FYI

**Comment by vscheuber** [comment]
We have completely eliminated all dependencies on gulp as a build tool with the help of one of our external contributors, @hfranklin .
