### ISSUE TITLE
Get and Delete OAuth2Client Apps by ID

### ISSUE THREAD

**Issue by aphillipohl** [rockcarver/frodo-lib#232]
When starting on writing tests for the OAuth2ClientOps the other tests delete any imported config first. I think there must be a way to delete and fetch apps by ID so it might be good to do that here.

**Comment by vscheuber** [comment]
Agreed. There is `getOAuth2Client(id)` in `OAuth2ClientApi.ts` but it should probably be passed through the ops layer in `OAuth2ClientOps.ts`.

BTW: Testing is a topic we may want to discuss as we have created a full mock suite for this. Checkout any of the test files, for example `ScriptOps.test.ts` or a more complex one, `Saml2Ops.test.ts`, as examples. I find the updating of mock response files and snapshots a bit tricky at times but I put a lot of details into the existing files that should explain the process fairly well. We simply haven't been able to achieve full test coverage, yet. Thank you for making test coverage part of your contribution, that is highly appreciated!

**Comment by vscheuber** [comment]
This was made available quite a while ago. See the [OAuth2Client API doc](https://rockcarver.github.io/frodo-lib/types/Reference.OAuth2Client.html).
