### ISSUE TITLE
Project not configured to use jest-babel when running tests

### ISSUE THREAD

**Issue by hfranklin** [rockcarver/frodo-lib#238]
## Frodo Library version
v0.18.9-4

## Describe the issue
The project does not seem to be configured to use jest-babel when running tests. This makes it difficult to run the test from IntelliJ (or other JetBrains IDEs).

**Comment by vscheuber** [comment]
@hfranklin we are using jest as our test framework but we are not currently using jest-babel, as our pipeline doesn't need it and our contributors so far have been manually invoking tests before committing work.

Can you propose the changes you have in mind? If they don't conflict with our pipeline and our current approach, I'd be happy to incorporate them!

**Comment by hfranklin** [comment]
@vscheuber I created a pull request with the changes. I don't see how to link it to this issue but here is the PR: https://github.com/rockcarver/frodo-lib/pull/239

**Comment by hfranklin** [comment]
This change should also remove the need to run gulp before running jest in the "test" script in package.json

**Comment by vscheuber** [comment]
I believe this has now become obsolete with our new setup.
