### ISSUE TITLE
Support for promotion API

### ISSUE THREAD

**Issue by frederic-luce** [rockcarver/frodo-lib#247]
Frodo-lib (and frodo-cli) should expose operations needed to handle promotions for Cloud Identity.
Is it already in the roadmap ?

**Comment by frederic-luce** [comment]
@vscheuber, I will soon start working on integrating Lock/Unlock and Promotion API in frodo-lib.
I will be able to contribute back this evolutions.
Do you already have some ideas about how these API should be integrated ?

**Comment by ashleyfrieze** [comment]
#289 is part of the solution to this.

**Comment by frederic-luce** [comment]
> #289 is part of the solution to this.

Yes, I did the same on my fork : https://github.com/frederic-luce/frodo-lib/blob/feature/promotion-api/src/ops/AuthenticateOps.ts#L47

**Comment by ashleyfrieze** [comment]
@frederic-luce - I'm having to build a call to promotions outside of FRODO for now. One thing to note is that we really need two commands here.

1. Pull a promotion up to _this_ environment from the one below
2. Check the lower environment for pending promotions

We probably don't want our pipeline to go to the effort of locking a FRIC environment to try a promotion when there's nothing to do. For full automated deployments, checking the lower environment with:

```
curl 'https://openam-customer-euw2-dev.id.forgerock.io/environment/promotion/report/provisional' \
 -H 'accept: application/json, text/plain, */*' \
 -H 'accept-api-version: protocol=1.0,resource=1.0' \
 -H 'authorization: Bearer ACCESS_TOKEN' \
 --compressed
```

is a good idea first - this will return a report with the changes in, or a report with empty arrays of changes, if there's nothing to do.

**Comment by frederic-luce** [comment]
@ashleyfrieze, yes I have this step in my CI job. I still don't know if I really need to do a dry-run promotion before the real one. Is the provisional report enough ?

**Comment by ashleyfrieze** [comment]
@frederic-luce - I think you can probably trust the provisional report. When you say you have it in your CI job, are you implementing it in FRODO for your CI job to use? Or are you running some scripts outside of FRODO?

I'm pitching some changes to FRODO to help, but we're building things FRODO can't do outside of FRODO in the hope that when we've got them working, we can get them added back in.

The hard part is probably the waiting loops and watching the state of promotion. Your pipeline may discover a half-finished lock/promotion and have to recover.

How are you getting on? Can I help?

**Comment by frederic-luce** [comment]
I use frodo-lib but it's outside of frodo-cli. 
I will use some kind of mutex in the pipeline to simplify the cases, but I think we can check the promotionId before each step to verify if it's the same as in our own lock call. If not, I will failed the whole pipeline.

**Comment by ashleyfrieze** [comment]
@frederic-luce  - yeah we're using FrodoLib too. We've built a driver app that works better for us than frodo cli.

My concern is that a failed pipeline may leave the environment locked and we'd either need to use the UI to unlock it, or build resilience into deployment jobs.

If the environment is locked, then either try a promotion, or try to unlock it. Likewise, if there's a promotion running, then wait for it, rather than start a new one.

Jobs work great until they don't.... :)
