### ISSUE TITLE
Access token acquired for service accounts should include promotion sccope

### ISSUE THREAD

**Issue by ashleyfrieze** [rockcarver/frodo-lib#290]
## Describe the solution you'd like
At the moment the access token for service accounts doesn't include the promotion scope.

#289 fixes this. Please consider merging it.

**Comment by vscheuber** [comment]
@ashleyfrieze I left a comment on the PR. I can't merge it without breaking every existing frodo service account. I'll have to think about this and solicit feedback from you and others how to do this best.

**Comment by vscheuber** [comment]
This was implemented with the changes for #391
