### ISSUE TITLE
Only "generic" encoding works for ESV secret 

### ISSUE THREAD

**Issue by atomicsamurai** [rockcarver/frodo-lib#369]
## Frodo Library version
```
cli: v2.0.0-43
lib: v2.0.0-59
node: v18.18.2
```

## Describe the issue
Frodo CLI helps says:
```
.
.
--encoding [encoding]        Secret encoding. Must be one of "generic", "pem", "base64hmac" (default: generic)
.
.
```
, but anything other than "generic" does not work.

**Comment by vscheuber** [comment]
@atomicsamurai  Last time I checked this was an API limitation. I think I just copied the description from the API docs and never updated it to reflect what the API supports today.
