### ISSUE TITLE
refactor: pure functions

### ISSUE THREAD

**Issue by adam-cyclones** [rockcarver/frodo-lib#37]
### What?
I would like to shoot for all functions to become pure functions to aid with the testing effort.

### Why?
Pure functions have controllable inputs and no external dependencies (apart from modules) this means:

- They're easier to reason about.
- They're easier to combine.
- They're easier to test.
- They're easier to debug.
- They're easier to parallelize.
- They're documentable

### Specifically why?
The global state should be passed into a function, decoupling it and allowing testable function calls

### what does it look like
Using an object based pattern for varadic args
```js
// Case 1: varadic shorthand
const {host, realm, password} = fromSomeSource;
authenticate({ host, realm, user, password });

// Case 2: setup a profile of stuff
const credentials = {username: 'foo', password: 'bar'};
// called
authenticate({ host, realm, ...credentials });

// Case 3: A test
test("set state to a bad realm", () => {
    const result = () => authenticate({ realm: 234, ...args});
    expect(result).toThrow();
})
``` 
Why use an object and de-structuring everywhere?
1. argument order does not matter nor does the way they are passed
2. arguments are clearly labeled
3. Global state can be completely removed in favor of passing objects around
4. you can combine how they are passed
5. names of things stay consistent because the names of arguments are pre-determined upstream

**Comment by vscheuber** [comment]
This has been implemented across all files and functions of frodo-lib.
