### ISSUE TITLE
Implement error handling pattern for methods with unusual amounts of REST calls like `exportFullConfiguration` (Renamed from: Move ConfigOps to CLI)

### ISSUE THREAD

**Issue by vscheuber** [rockcarver/frodo-lib#392]
ConfigOps is the module for full export and import. Because of its nature of performing a great many API calls it is prone to failure. Therefore it was implemented in a non-throwing way, printing errors it encounters while performing its task. That goes against the contract we agreed on with the library: The library always throws.

In order to adhere to this contract, it appears the best move would be to move the whole module as is into the CLI.

**Comment by vscheuber** [comment]
@phalestrivir tagging you here for your input. You implemented the functionality and I was wondering if you had good reasons to put it in the library vs implementing it fully in the CLI? If you have no objections, I'll move it.

**Comment by vscheuber** [comment]
@phalestrivir I have decided to investigate possible patterns that would allow the functionality to remain in frodo-lib. I find it incredibly powerful and would hate to lose it in the library.

I see 2 possible patterns that would allow us to keep it in the library and still abide by the contract of informing the client of errors (up to this point we have been doing this by throwing):

Pattern 1:
Use a structured response which contains the results and any errors incurred while generating the result:
```
{
  result: any;
  errors: Error[];
}
```

Pattern 2:
Allow the client to pass an error variable, which the library then populates with an array of errors while returning the result:
```
exportFullConfiguration(
  options: FullExportOptions,
  errors: Error[]
): Promise<FullExportInterface>;
```

I believe both patterns would work for complex composite functions like `exportJourney` and `exportFullConfiguration`. I prefer pattern 2, as it leaves retrieval of errors optional and in the control of the client.

Thoughts?

**Comment by phalestrivir** [comment]
Yes, I think that both would be reasonable, but I like pattern 2 better that way the client can optionally handle the errors like you said. Additionally, I think it helps keep it consistent with the other export methods in the library that only return the exported data and not errors as well.
