### ISSUE TITLE
frodo error when importing exported oauth client

### ISSUE THREAD

**Issue by rjeghanathan** [rockcarver/frodo-lib#393]
## Frodo Library version
Installed versions:
cli: v2.0.0-51
lib: v2.0.0-72
node: v18.18.2

## Describe the issue
When an Oauth client is exported using 
`frodo oauth client export TEST-CLIENT <realm> <conn-profile>`

and attempt to reimport using 
`frodo oauth client import -f TEST-CLIENT.oauth2.app.json <realm> <conn-profile>`

I am getting the following error:

`Error: Import error:
Cannot convert undefined or null to object
    at /snapshot/frodo-cli-next-20240319-691916-r5r0kj/node_modules/@rockcarver/frodo-lib/cjs/ops/OAuth2ClientOps.js:728:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/snapshot/frodo-cli-next-20240319-691916-r5r0kj/node_modules/@rockcarver/frodo-lib/cjs/ops/OAuth2ClientOps.js:24:103)
    at _throw (/snapshot/frodo-cli-next-20240319-691916-r5r0kj/node_modules/@rockcarver/frodo-lib/cjs/ops/OAuth2ClientOps.js:25:291)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

This is not just related to next builds, also can see this in stable builds.

**Comment by vscheuber** [comment]
Hi @rjeghanathan thank you for reporting this. I'll try and look into this today.

**Comment by vscheuber** [comment]
Ok, so quick analysis and first thoughts:

**Comment by rjeghanathan** [comment]
Hi @vscheuber 
I am on a local AM 7.1.2 running on tomcat9 and not on ID cloud, not sure if this has something to do with this.

The exact commands as below:
here fr.ftest is the profile and external is the realm
```
frodo oauth client export -i testclient fr.ftest external
Connected to https://am.example.com/openam [external] as user amadmin
✔ Exported testclient to testclient.oauth2.app.json.
frodo oauth client import -f testclient.oauth2.app.json fr.ftest external
Connected to https://fr.example.com/openam [external] as user amadmin
✖ Error importing testclient.oauth2.app.json.
Error: Import error:
Cannot convert undefined or null to object
    at /snapshot/frodo-cli-next-20240319-691916-r5r0kj/node_modules/@rockcarver/frodo-lib/cjs/ops/OAuth2ClientOps.js:728:13
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/snapshot/frodo-cli-next-20240319-691916-r5r0kj/node_modules/@rockcarver/frodo-lib/cjs/ops/OAuth2ClientOps.js:24:103)
    at _throw (/snapshot/frodo-cli-next-20240319-691916-r5r0kj/node_modules/@rockcarver/frodo-lib/cjs/ops/OAuth2ClientOps.js:25:291)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I am also attaching the exported file for reference.
[testclient.oauth2.app.json](https://github.com/rockcarver/frodo-lib/files/14667980/testclient.oauth2.app.json)

**Comment by vscheuber** [comment]
@rjeghanathan thank you! Confirmed and with your sample export reproduced. The issue is a backwards compatibility bug I introduced when implementing support for the new oauth2 provider overrides on oauth2 clients. I should have a new pre-release out shortly with a fix.

**Comment by vscheuber** [comment]
@rjeghanathan the issue is fixed in frodo library but I have yet to release a new version of the CLI which uses the new library with the fix. I hope to be able to do that sometime tomorrow (well, later today).

**Comment by rjeghanathan** [comment]
@vscheuber I validated this and is working fine now. I am able to export and import OAuth clients in 7.1.2 version of AM
