### ISSUE TITLE
Add support for `base64aes` encoding for ESV secrets

### ISSUE THREAD

**Issue by atomicsamurai** [rockcarver/frodo-lib#394]
ID Cloud can now use AES keys as ESV secrets. frodo should add import support for this new feature.

**Comment by vscheuber** [comment]
@atomicsamurai are you planning on doing this work?

**Comment by vscheuber** [comment]
I believe the changes to support this are minimal. @atomicsamurai let me know if what I'm doing here is not enough. Should check-in what I think is required very soon.
