### ISSUE TITLE
updateConfigEntity to allow the option for waitForCompletion

### ISSUE THREAD

**Issue by sayers-pi** [rockcarver/frodo-lib#448]
## Describe the solution you'd like

When updating the managed json and access json I was getting a 403 if I tried to create an internal role immediately after

Couldn't find a way to pass this through in frodo-lib, so with the help of @conorbarford-ping we resolved this by replacing the commented code with the following

```
    // await this.#frodo.idm.config.updateConfigEntity(type, generatedConfig);

    const urlString = util.format(
      `%s/openidm/config/${type}?waitForCompletion=true`,
      this.#frodo.utils.getHostBaseUrl(this.#frodo.state.getHost())
    );

    await generateIdmApi({ state: this.#frodo.state }).put(urlString, generatedConfig);
```

**Comment by vscheuber** [comment]
@sayers-pi @conorbarford-ping thank you for pointing this out! Before I tackle this, I will research where this parameter applies and if we should use it for all applicable IDM API calls by default and allow a developer to turn it off if they want to "fire and forget" but by default have it set to true? Any thoughts? Checking the documentation just quickly I didn't see it called out as a global option, so now I'm thinking I may have to research more and find out where it's applicable and where it isn't.

**Comment by conorbarford-ping** [comment]
hey, this is where I found it in the docs which seems to suggest everything under `/openidm/config/` is applicable: https://backstage.forgerock.com/docs/idm/7.1/setup-guide/configuring-over-rest.html

those docs are for IDM though and I didn't spend any time seeing if the Cloud docs had anything similar
