### ISSUE TITLE
Implement testing

### ISSUE THREAD

**Issue by adam-cyclones** [rockcarver/frodo-lib#45]
Given the nonfunctional nature of this ticket, I will omit the template, this ticket adds jest and a series of tests to 

- test the Interface (Interface tests)
- test the results of an action taken using Frodo (Functional tests)
- the internal workings (unit tests)

**Comment by vscheuber** [comment]
Testing has significantly improved and test coverage is constantly improving. Closing this issue as we have adapted a culture of test automation in the frodo project.
