### ISSUE TITLE
Provide analyze feature 

### ISSUE THREAD

**Issue by CharanMann** [rockcarver/frodo-lib#50]
frodo should provide analyze feature to generate a report for current deployment. This report should provide: 

1. List of journeys 
2. Customizations including Scripted and Java nodes, if any 
3. Applications: OAuth2, SAML entities, Policies 
4. Identity sources

**Comment by vscheuber** [comment]
@CharanMann , I think the new s2s tooling provides all these capabilities. Closing this. Please re-open if you think there is something Frodo should do.
