### ISSUE TITLE
Make lib stateless

### ISSUE THREAD

**Issue by adam-cyclones** [rockcarver/frodo-lib#7]
Remove the concept of global state storage from lib and pass all `storage` which should be stated, in as pure functions for testing and purposes relating to individual client requirements. 

``` js
// some client

const state = {
    username: '',
    password: '',
}

someOpsBinding({
    state
});
```

### Why?
I have a client that only does anything with scripts, instead of just passing state into a couple of opsBindings functions I have to import a reference to lib-state and use some getters and setters which already expose a raw key.

**Comment by vscheuber** [comment]
This is now possible with the new typed and instantiable state implementation. A state can be instantiated with a StateInterface like in the sample code. Closing as complete.
