### ISSUE TITLE
src folder reorg?

### ISSUE THREAD

**Issue by adam-cyclones** [rockcarver/frodo-lib#8]
For simplicity, perhaps we can flatten `src` move all `utils`,  `templates` parallel with `ops`?

**Some thoughts on OPS**
We have recontextualized frodo and are striving to create a separation from client and lib, a fresh start.. so I propose that we change the name `ops` which to me sounds like dev-ops to `bindings` or `public`, technically it's `API` but as the `API` is referring to REST calls its a little confusing.

**Comment by vscheuber** [comment]
We have settled on `ops` and have no plans on changing unless there is a pressing reason.
